ThisBuild / scalaVersion := "3.9.0"
ThisBuild / organization := "io.7mind.cq"
ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / scalacOptions ++= Seq("-deprecation", "-feature", "-unchecked")
ThisBuild / javaOptions ++= IO.readLines((ThisBuild / baseDirectory).value / ".jvmopts")

val izumiVersion = "1.2.25"
val circeVersion = "0.14.16"
val http4sVersion = "0.23.37"
val runtimeClasspath = taskKey[String]("Resolved runtime classpath for JVM and native launchers")
val sourceBuild = taskKey[String]("Source revision this build is made from, as dev/source-revision reports it")

lazy val contracts = project.in(file("contracts")).settings(
  Compile / unmanagedSourceDirectories += (ThisBuild / baseDirectory).value / "generated" / "scala",
  Compile / unmanagedResourceDirectories += (ThisBuild / baseDirectory).value / "generated" / "resources",
  libraryDependencies += "io.circe" %% "circe-parser" % circeVersion,
)

lazy val core = project.in(file("core")).dependsOn(contracts).settings(
  libraryDependencies ++= Seq(
    "io.7mind.izumi" %% "fundamentals-bio" % izumiVersion,
    "io.7mind.izumi" %% "distage-core" % izumiVersion,
    "dev.zio" %% "zio" % "2.1.26",
  ),
)

lazy val host = project.in(file("host")).dependsOn(core)

lazy val server = project.in(file("server")).dependsOn(core, host).settings(
  runtimeClasspath := Def.uncached {
    val converter = fileConverter.value
    (Runtime / fullClasspath).value.map(entry => converter.toPath(entry.data).toString).mkString(java.io.File.pathSeparator)
  },
  libraryDependencies ++= Seq(
    "io.7mind.izumi" %% "distage-framework" % izumiVersion,
    "io.7mind.izumi" %% "fundamentals-bio" % izumiVersion,
    "dev.zio" %% "zio-interop-cats" % "23.1.0.13",
    "org.http4s" %% "http4s-ember-server" % http4sVersion,
    "org.http4s" %% "http4s-dsl" % http4sVersion,
    "org.postgresql" % "postgresql" % "42.7.13",
    "org.tomlj" % "tomlj" % "2.2.0",
    "io.7mind.izumi" %% "distage-testkit-scalatest" % izumiVersion % Test,
    "org.scalatest" %% "scalatest" % "3.2.20" % Test,
  ),
  // Read at every build and never cached: the same sources can be built from another commit or from a modified tree.
  sourceBuild := Def.uncached {
    val root = (ThisBuild / baseDirectory).value
    scala.util.Try(scala.sys.process.Process(Seq((root / "dev" / "source-revision").toString, root.toString)).!!.trim).toOption
      .filter(_.matches("(clean|modified) ([0-9a-f]{40}|[0-9a-f]{64})|undetermined .+"))
      .getOrElse("undetermined dev/source-revision could not be run")
  },
  // Compiled in as a constant, so the JVM classpath and the native image built from it carry the same value.
  Compile / sourceGenerators += Def.task {
    val file = (Compile / sourceManaged).value / "cq" / "server" / "ProducingBuild.scala"
    val Array(kind, detail) = sourceBuild.value.split(" ", 2)
    val text = detail.filter(character => character.isLetterOrDigit || " ._/:-".contains(character))
    val value = kind match {
      case "clean" => s"""SourceBuild.Clean(GitCommit("$text"))"""
      case "modified" => s"""SourceBuild.Modified(GitCommit("$text"))"""
      case _ => s"""SourceBuild.Undetermined("$text")"""
    }
    val content = "package cq.server\n\nimport cq.api.{GitCommit, SourceBuild}\n\n" +
      "/** Generated by build.sbt from dev/source-revision: the source revision this build was compiled from. */\n" +
      s"object ProducingBuild {\n  val value: SourceBuild = $value\n}\n"
    if (!file.exists || IO.read(file) != content) IO.write(file, content)
    Seq(file)
  }.taskValue,
  Compile / mainClass := Some("cq.server.Main"),
  Compile / run / fork := true,
  Test / fork := true,
  Test / javaOptions += s"-Dcq.test.sourceRoot=${(ThisBuild / baseDirectory).value}",
  Test / javaOptions += {
    val converter = fileConverter.value
    "-Dcq.test.classpath=" + (Test / fullClasspath).value.map(entry => converter.toPath(entry.data).toString).mkString(java.io.File.pathSeparator)
  },
)

lazy val root = project.in(file(".")).aggregate(contracts, core, host, server).settings(
  publish / skip := true,
)
