import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { writeFile } from 'node:fs/promises';

export async function workspaceChecks(browser, storageState, origin, evidence) {
  const headers = { Authorization: `Bearer ${process.env.CQ_TOKEN}`, 'CQ-Session': randomUUID(),
    'CQ-Protocol-Version': '0.1.0', 'Content-Type': 'application/json' };
  async function post(command) {
    const response = await fetch(`${origin}/api/call`, { method: 'POST', headers, body: JSON.stringify(command) });
    assert.equal(response.status, 200, await response.clone().text());
    const result = await response.json(); assert.equal(result.Failed, undefined); return result;
  }
  const project = { value: randomUUID() };
  await post({ Initialize: { config: { project, endpoint: origin, name: `Workspace ${project.value}` } } });
  const draft = title => ({ title, body: 'Workspace interaction fixture', labels: [], archived: false, citations: [],
    content: { Task: { status: 'Ready', acceptance: ['Keep keyboard context during updates'], result: null, validation: [] } } });
  const change = mutations => post({ Change: { input: { project, change: { request: { value: randomUUID() }, fences: [], reason: 'Workspace fixture', mutations } } } });
  const created = await change(['Keyboard A', 'Keyboard B'].map(title => ({ Create: { draft: draft(title) } })));
  const context = await browser.newContext({ storageState, viewport: { width: 1440, height: 900 } });
  await context.tracing.start({ screenshots: true, snapshots: true, sources: true });
  const page = await context.newPage(); const errors = []; const cases = [];
  page.on('pageerror', error => errors.push(String(error)));
  try {
    await page.goto(origin); await page.getByText('Connection: ALIVE', { exact: true }).waitFor();
    await page.getByLabel('Project', { exact: true }).selectOption(project.value);
    const first = page.getByRole('button', { name: 'T1 · Keyboard A', exact: true });
    await first.waitFor(); await page.getByText('Data: current', { exact: true }).waitFor();
    await first.focus();
    const second = created.Changed.ack.items[1];
    await change([{ Replace: { id: second.id, expected: second.revision, draft: draft('Keyboard B updated') } }]);
    await page.getByRole('button', { name: 'T2 · Keyboard B updated', exact: true }).waitFor();
    assert.equal(await first.evaluate(node => node === document.activeElement), true, 'Live result refresh must retain keyboard focus');
    cases.push('focus during live update');
    await first.press('ArrowDown');
    const secondRow = page.getByRole('button', { name: 'T2 · Keyboard B updated', exact: true });
    assert.equal(await secondRow.evaluate(node => node === document.activeElement), true);
    await secondRow.press('Enter'); await page.getByRole('heading', { name: 'T2 · Keyboard B updated', exact: true }).waitFor();
    assert.equal(await secondRow.getAttribute('aria-current'), 'true');
    assert.equal(await secondRow.locator('xpath=ancestor::tr').locator('.item-status').textContent(), 'Ready');
    const detail = page.getByRole('article', { name: 'Item workspace', exact: true });
    await secondRow.press('ArrowRight'); assert.equal(await detail.evaluate(node => node === document.activeElement), true);
    await detail.press('Escape'); assert.equal(await secondRow.evaluate(node => node === document.activeElement), true);
    await secondRow.press('F6'); assert.equal(await detail.evaluate(node => node === document.activeElement), true);
    await detail.press('Shift+F6'); assert.equal(await page.getByRole('region', { name: 'Results', exact: true }).evaluate(node => node === document.activeElement), true);
    await page.keyboard.press('Control+k');
    const query = page.getByRole('combobox', { name: 'Search query', exact: true });
    assert.equal(await query.evaluate(node => node === document.activeElement && node.closest('header') !== null), true);
    assert.equal(await page.getByLabel('Project', { exact: true }).evaluate(node => node.closest('header') !== null), true);
    cases.push('keyboard selection, detail return and pane/query focus');
    const heading = page.getByRole('heading', { name: 'T2 · Keyboard B updated', exact: true });
    await page.getByRole('button', { name: 'Close item view', exact: true }).click();
    await detail.waitFor({ state: 'hidden' }); await heading.waitFor({ state: 'detached' });
    assert.equal(await secondRow.getAttribute('aria-current'), 'false');
    assert.equal(await secondRow.evaluate(node => node === document.activeElement), true, 'Closing returns focus to the results');
    await secondRow.press('Enter'); await heading.waitFor(); await detail.waitFor();
    await secondRow.press('ArrowRight'); await detail.press('Escape'); await secondRow.press('Escape');
    await detail.waitFor({ state: 'hidden' }); assert.equal(await secondRow.getAttribute('aria-current'), 'false');
    assert.equal(await secondRow.evaluate(node => node === document.activeElement), true, 'Escape close keeps focus in the results');
    await secondRow.press('F6');
    assert.equal(await page.locator('#navigation-pane').evaluate(node => node === document.activeElement), true, 'F6 skips the hidden item pane');
    await page.keyboard.press('Shift+F6');
    assert.equal(await page.getByRole('region', { name: 'Results', exact: true }).evaluate(node => node === document.activeElement), true);
    await secondRow.focus(); await secondRow.press('Enter'); await heading.waitFor(); await detail.waitFor();
    assert.equal(await secondRow.getAttribute('aria-current'), 'true');
    cases.push('item view close button and Escape close clear selection, hide the pane, F6 skips it and selection reopens it');
    await page.getByRole('button', { name: 'Tasks', exact: true }).click();
    assert.equal(await query.inputValue(), 'ledger:Tasks');
    await page.getByText('Data: current', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'All items', exact: true }).click(); assert.equal(await query.inputValue(), '');
    await page.getByText('Data: current', { exact: true }).waitFor();
    cases.push('navigation writes visible query');
    // D72 / Decision 8: a navigation filter whose fully loaded results omit the selection closes the item view.
    await change([{ Create: { draft: { title: 'Stale selection defect', body: 'Workspace interaction fixture', labels: [], archived: false, citations: [],
      content: { Defect: { status: 'Open', severity: 'Medium', observed: 'Stale detail', expected: 'Hidden detail', reproduction: 'Switch filters', cause: null, resolution: [] } } } } }]);
    const defectRow = page.getByRole('button', { name: 'D1 · Stale selection defect', exact: true }); await defectRow.waitFor();
    const currentRows = page.locator('#results-pane [aria-current=true]');
    await page.getByRole('button', { name: 'Tasks', exact: true }).click(); await defectRow.waitFor({ state: 'detached' });
    await page.getByText('Data: current', { exact: true }).waitFor();
    await heading.waitFor(); assert.equal(await detail.isVisible(), true, 'A filter that still lists the selection keeps the item view');
    assert.equal(await secondRow.getAttribute('aria-current'), 'true');
    cases.push('filter switch still listing the selection keeps the item view');
    const stale = { taskRowPresent: null, detailVisible: null, headingCount: null, selectedRows: null };
    try {
      await page.getByRole('button', { name: 'Defects', exact: true }).click(); assert.equal(await query.inputValue(), 'ledger:Defects');
      await defectRow.waitFor(); await secondRow.waitFor({ state: 'detached' }); await page.getByText('Data: current', { exact: true }).waitFor();
      await page.waitForFunction(() => document.getElementById('detail-pane').hidden, null, { timeout: 5000 }).catch(() => {});
      Object.assign(stale, { taskRowPresent: await secondRow.count(), detailVisible: await detail.isVisible(), headingCount: await heading.count(), selectedRows: await currentRows.count() });
      assert.equal(stale.detailVisible, false, 'stale task detail remains visible after switching to Defects');
      assert.equal(stale.headingCount, 0, 'stale task heading remains after switching to Defects'); assert.equal(stale.selectedRows, 0);
    } finally { await writeFile(`${evidence}/workspace-stale-selection.json`, JSON.stringify(stale, null, 2)); }
    await page.getByRole('button', { name: 'All items', exact: true }).click(); await secondRow.waitFor();
    await page.getByText('Data: current', { exact: true }).waitFor();
    assert.equal(await detail.isVisible(), false, 'Returning to a listing filter does not restore the cleared selection');
    assert.equal(await heading.count(), 0); assert.equal(await currentRows.count(), 0);
    await secondRow.click(); await heading.waitFor(); await detail.waitFor(); assert.equal(await secondRow.getAttribute('aria-current'), 'true');
    cases.push('filter switch omitting the selection clears it and hides the item view; selecting reopens it');
    const navigation = page.getByRole('navigation', { name: 'Navigation', exact: true });
    const results = page.getByRole('region', { name: 'Results', exact: true });
    assert.equal(await page.getByRole('separator', { name: 'Resize navigation', exact: true }).count(), 0);
    const resultSplitter = page.getByRole('separator', { name: 'Resize results', exact: true });
    const width = locator => locator.evaluate(node => node.getBoundingClientRect().width);
    const navigationWidth = await width(navigation); const initialWidth = await width(results);
    await resultSplitter.focus(); await resultSplitter.press('ArrowRight'); assert.equal(await width(results), initialWidth + 16);
    await resultSplitter.press('Home'); assert.equal(await width(results), Number(await resultSplitter.getAttribute('aria-valuemin')));
    await resultSplitter.press('End'); assert.equal(await width(results), Number(await resultSplitter.getAttribute('aria-valuemax')));
    assert.equal(await width(navigation), navigationWidth);
    assert.ok(await width(detail) >= 300);
    await page.setViewportSize({ width: 980, height: 900 });
    await page.waitForFunction(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth);
    assert.ok(await width(detail) >= 300);
    assert.equal(await width(navigation), navigationWidth);
    await page.setViewportSize({ width: 1440, height: 900 }); await resultSplitter.press('Home'); await resultSplitter.press('ArrowRight');
    const beforeDrag = await width(results); const box = await resultSplitter.boundingBox(); assert.notEqual(box, null);
    await page.mouse.move(box.x + box.width / 2, box.y + 40); await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 84, box.y + 40); await page.mouse.up();
    assert.equal(await width(results), beforeDrag + 84); cases.push('keyboard/pointer resizing and viewport bounds');
    const status = page.getByLabel('Workspace status', { exact: true });
    assert.equal(await status.locator('kbd').count(), 7);
    assert.equal(await status.locator('kbd [aria-hidden=true]').filter({ hasText: '↵' }).count(), 1);
    assert.match(await status.getByRole('group', { name: 'Keyboard shortcuts', exact: true }).ariaSnapshot(), /Enter select/);
    assert.equal((await navigation.textContent()).includes('Ctrl+K'), false);
    const assertStatusVisible = async () => {
      const bounds = await status.boundingBox();
      assert.ok(bounds !== null && bounds.y >= 0 && bounds.y + bounds.height <= page.viewportSize().height);
    };
    await assertStatusVisible(); cases.push('fixed navigation and persistent outlined keyboard guidance');
    await change(Array.from({ length: 48 }, (_, index) => ({ Create: { draft: draft(`Long row ${index} ` + 'unbroken'.repeat(12)) } })));
    await page.getByText('40 items · more available', { exact: true }).waitFor();
    const resultBox = await results.boundingBox(); assert.notEqual(resultBox, null);
    const navigationScroll = await navigation.evaluate(node => node.scrollTop);
    await page.mouse.move(resultBox.x + resultBox.width / 2, resultBox.y + 100); await page.mouse.wheel(0, 1400);
    await page.waitForFunction(() => document.getElementById('results-pane').scrollTop > 0);
    assert.equal(await navigation.evaluate(node => node.scrollTop), navigationScroll);
    assert.equal(await page.evaluate(() => document.scrollingElement.scrollTop), 0);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true);
    cases.push('independent result scrolling');
    await first.click(); await page.getByRole('heading', { name: 'T1 · Keyboard A', exact: true }).waitFor();
    const metrics = page.getByRole('region', { name: 'Usage metrics', exact: true });
    await metrics.getByText(/^Usage · T1:/).waitFor(); await metrics.getByText(/^Observed /).waitFor();
    assert.match(await metrics.textContent(), /known tokens.*unknown measurements.*estimated measurements.*cursor/);
    await page.screenshot({ path: `${evidence}/workspace-desktop.png`, fullPage: true });
    await page.getByRole('button', { name: 'Edit current revision', exact: true }).click();
    const body = page.getByLabel('body', { exact: true }); const local = 'Unsaved local text: ' + 'unbroken'.repeat(240);
    await body.fill(local);
    await change([{ Replace: { id: second.id, expected: { value: '2' }, draft: draft('Live update while typing') } }]);
    await page.getByRole('button', { name: 'T2 · Live update while typing', exact: true }).waitFor();
    assert.equal(await body.inputValue(), local); assert.equal(await body.evaluate(node => node === document.activeElement), true);
    cases.push('live edits preserve draft and text focus');
    for (const viewportWidth of [920, 390, 320]) {
      await page.setViewportSize({ width: viewportWidth, height: 844 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true, `Page overflow at ${viewportWidth}`);
      assert.equal(await page.getByRole('separator', { name: /^Resize (navigation|results)$/ }).count(), 0, 'Narrow layout must hide pane separator focus targets');
      await assertStatusVisible();
      assert.equal(await status.getByRole('group', { name: 'Keyboard shortcuts', exact: true }).isVisible(), false, 'Narrow layout hides keyboard guidance to keep the status bar compact');
      assert.equal(await body.inputValue(), local);
      const bounds = await page.locator('.pane').evaluateAll(nodes => nodes.map(node => ({ id: node.id, width: node.clientWidth, scroll: node.scrollWidth })));
      assert.ok(bounds.filter(value => value.id !== 'results-pane').every(value => value.scroll <= value.width + 1), JSON.stringify(bounds));
      if (viewportWidth === 390) await page.screenshot({ path: `${evidence}/workspace-narrow.png`, fullPage: true });
    }
    cases.push('narrow layouts and unbroken draft overflow');
    await page.setViewportSize({ width: 1440, height: 900 });
    const other = { value: randomUUID() };
    await post({ Initialize: { config: { project: other, endpoint: origin, name: `Other ${other.value}` } } });
    await page.reload(); await page.getByText('Connection: ALIVE', { exact: true }).waitFor();
    await page.getByLabel('Project', { exact: true }).selectOption(other.value);
    await page.getByText('No matching items.', { exact: true }).waitFor();
    await page.getByLabel('Project', { exact: true }).selectOption(project.value);
    await first.click(); await page.getByRole('button', { name: 'Edit current revision', exact: true }).click();
    assert.equal(await body.inputValue(), local); cases.push('draft survives reload and project switching');
    await metrics.getByText(/^Observed /).waitFor(); await context.setOffline(true);
    await metrics.getByText(/^Stale · Observed /).waitFor(); await context.setOffline(false);
    await metrics.getByText(/^Observed /).waitFor(); cases.push('usage observation and stale labels');
    console.log('Chromium workspace: live focus, keyboard navigation, query shortcuts, resizing, independent scrolling, narrow overflow, draft preservation and metric freshness passed');
    assert.deepEqual(errors, []);
  } finally {
    await writeFile(`${evidence}/workspace-results.json`, JSON.stringify({ cases, errors }, null, 2));
    await page.screenshot({ path: `${evidence}/workspace-last.png`, fullPage: true });
    await context.tracing.stop({ path: `${evidence}/workspace-trace.zip` }); await context.close();
  }
}
