package cq.server

import cq.api.*
import cq.host.{CommandAsset, DispatchWaits, DriverAssets, HostFiles, PiAssets, WorkflowAssets}
import io.circe.{Json, parser}
import java.nio.file.{Files, Path}

final class AttachedAssets(schemas: McpSchemas, workflows: WorkflowAssets) {
  private val MaxConfigBytes = 1024 * 1024
  private val CodexHeader = "# Generated by cq configure; contains no credentials.\n"
  private val ClaudeSettings = Path.of(".claude/settings.local.json")
  private val CodexHooks = Path.of(".codex/hooks.json")
  /** The Claude Code permission rule that allows the session to run `cq wait` without being asked. It is the exact command line, with
    * no wildcard: a prefix rule is a prefix match on the command string, and the session is given a command that needs no argument. */
  def claudeWaitRule(executable: Path): String = s"Bash($executable wait)"
  /** The Claude Code permission rules that let the session's file tools read and write, without being asked, the worktrees a host of
    * this state root opens (I30): `<stateRoot>/<session>/workspaces/<attempt>/tree/` and what is below it. They cover the tree of
    * every workspace of every session under the state root, a child's and a check's as much as the Governor's own, because session
    * and attempt are known only when a workspace exists and a rule names no narrower set. They do not cover the host's records
    * beside a tree (`workspace.json`, the lock) or anything else under the state root. A rule that begins with `//` is rooted at the
    * filesystem, each `*` stands for one directory, and an `Edit` rule covers every file-writing tool. A state root reached through
    * a symbolic link, its own or an ancestor's, is named both ways: the session is given the path as the settings write it.
    * No rule can make such a workspace the working directory of the session's shell: see docs/interactive.md. */
  def claudeWorkspaceRules(project: Path, stateRoot: String): List[String] = {
    val written = project.resolve(stateRoot).toAbsolutePath.normalize()
    // The host creates the state root when it first starts, so the link may be an ancestor of a directory that does not exist yet.
    val existing = Iterator.iterate(written)(_.getParent).takeWhile(_ != null).find(Files.exists(_)).getOrElse(written.getRoot)
    val real = existing.toRealPath().resolve(existing.relativize(written))
    List(written, real).distinct.flatMap { root =>
      require(!root.toString.exists(character => character.isWhitespace || "()*?[]{}!\\".contains(character)),
        "The state root path cannot be named in a Claude permission rule: it contains whitespace, a parenthesis or a pattern character")
      List("Edit", "Read").map(tool => s"$tool(/$root/*/workspaces/*/tree/**)")
    }
  }
  private def quoted(value: String): String = Json.fromString(value).noSpaces
  def write(harness: Harness, root: Path, settingsPath: Path, executable: Path, replace: Boolean, replaceStatusLine: Boolean): List[Path] = {
    if (harness == Harness.Codex) {
      val file = root.resolve(".codex/config.toml")
      require(!Files.exists(file) || HostFiles.text(file, MaxConfigBytes).startsWith(CodexHeader),
        "Existing .codex/config.toml is user-owned. Export into an empty directory and merge its mcp_servers.cq table into this file; CQ will not overwrite unrelated TOML settings")
    }
    val assets = plan(harness, root, root, settingsPath, executable, replace, replaceStatusLine)
    // JSON configuration CQ merges into is rewritten in place; every other asset is a generated file guarded by --replace.
    val merged = assets.map(_.path).filter(path => harness == Harness.Claude && Set(Path.of(".mcp.json"), ClaudeSettings)(path) || path == CodexHooks).toSet
    workflows.writeAssets(assets, root, replace, merged)
  }
  def exportAssets(harness: Harness, destination: Path, project: Path, settingsPath: Path, executable: Path): List[Path] = {
    require(project.isAbsolute && project.normalize() == project, "Integration project must be an absolute normalized directory")
    workflows.writeAssets(plan(harness, destination, project, settingsPath, executable, false, false), destination, false, Set.empty)
  }
  def plan(harness: Harness, root: Path, project: Path, settingsPath: Path, executable: Path, replace: Boolean, replaceStatusLine: Boolean): List[CommandAsset] = {
    require(executable.isAbsolute && Files.isExecutable(executable) && Files.isRegularFile(executable), "CQ executable must be an absolute executable file")
    val settings = HostFiles.read(settingsPath.toRealPath(), SupervisorSettings_JsonCodec, MaxConfigBytes)
    val profiles = settings.harnesses.map(SupervisorConfig.profile)
    require(profiles.nonEmpty && profiles.map(_.harness).distinct.size == profiles.size, "Harness settings must have unique verified routes")
    require(settings.harnesses.exists(_.harness == harness), "Settings do not include this harness route")
    require(harness == Harness.Claude || !replaceStatusLine,
      s"${DriverAssets.StatusLineFlag} applies only to claude: cq configure installs no status line for ${harness.toString.toLowerCase}")
    // The host is told which executable this integration approved for `cq wait`: it names that command line to the session.
    val args = List("host", harness.toString.toLowerCase, "--settings", settingsPath.toString, "--executable", executable.toString)
    val command = Json.obj("command" -> Json.fromString(executable.toString), "args" -> Json.arr(args.map(Json.fromString)*))
    val integration = harness match {
      case Harness.Claude =>
        val file = root.resolve(".mcp.json")
        val current = if (Files.exists(file)) parser.parse(HostFiles.text(file.toRealPath(), MaxConfigBytes)).fold(throw _, identity) else Json.obj()
        require(current.isObject, "Claude MCP configuration must be an object")
        val servers = current.hcursor.downField("mcpServers").focus.getOrElse(Json.obj())
        require(servers.isObject, "Claude mcpServers must be an object")
        // Claude Code's per-server tool-call limit, in milliseconds: its default is far longer and its MCP_TOOL_TIMEOUT may be shorter
        // than a dispatch call that waits.
        val value = command.deepMerge(Json.obj("type" -> Json.fromString("stdio"), "timeout" -> Json.fromLong(DispatchWaits.AttachedHarnessSeconds * 1000)))
        require(servers.hcursor.downField("cq").focus.forall(_ == value) || replace, "Claude cq entry differs; use --replace to replace that entry")
        val localFile = root.resolve(".claude/settings.local.json")
        val local = if (Files.exists(localFile)) parser.parse(HostFiles.text(localFile.toRealPath(), MaxConfigBytes)).fold(throw _, identity) else Json.obj()
        require(local.isObject, "Claude .claude/settings.local.json must be an object")
        val enabled = local.hcursor.downField("enabledMcpjsonServers").focus.getOrElse(Json.arr())
        require(enabled.isArray, "Claude enabledMcpjsonServers in .claude/settings.local.json must be an array")
        val cq = Json.fromString("cq")
        val approved = if (enabled.asArray.exists(_.contains(cq))) enabled else enabled.mapArray(_ :+ cq)
        // Claude records a declined server in disabledMcpjsonServers, which overrides the approval; remove only the cq entry.
        val disabled = local.hcursor.downField("disabledMcpjsonServers").focus
        require(disabled.forall(_.isArray), "Claude disabledMcpjsonServers in .claude/settings.local.json must be an array")
        val settingsLocal = disabled.fold(local)(value => local.mapObject(_.add("disabledMcpjsonServers", value.mapArray(_.filterNot(_ == cq)))))
        require(!executable.toString.exists(character => character.isWhitespace || "()*".contains(character)),
          "The CQ executable path cannot be named in a Claude permission rule: it contains whitespace, a parenthesis or an asterisk")
        val permissions = settingsLocal.hcursor.downField("permissions").focus.getOrElse(Json.obj())
        require(permissions.isObject, "Claude permissions in .claude/settings.local.json must be an object")
        val allowed = permissions.hcursor.downField("allow").focus.getOrElse(Json.arr())
        require(allowed.isArray, "Claude permissions.allow in .claude/settings.local.json must be an array")
        val rules = (claudeWaitRule(executable) :: claudeWorkspaceRules(project, settings.stateRoot)).map(Json.fromString)
        val permitted = settingsLocal.mapObject(_.add("permissions", permissions.mapObject(_.add("allow",
          allowed.mapArray(present => present ++ rules.filterNot(present.contains))))))
        val driven = DriverAssets.statusLine(DriverAssets.hooks(permitted.mapObject(_.add("enabledMcpjsonServers", approved)), executable, harness, ClaudeSettings.toString),
          executable, replaceStatusLine, ClaudeSettings.toString)
        List(CommandAsset(Path.of(".mcp.json"), current.mapObject(_.add("mcpServers", servers.mapObject(_.add("cq", value)))).spaces2 + "\n"),
          CommandAsset(ClaudeSettings, driven.spaces2 + "\n"))
      case Harness.Codex =>
        val forwarded = (Set("CQ_TOKEN", "CQ_TOKEN_FILE", "CQ_SETTINGS", "CODEX_HOME") ++ settings.harnesses.flatMap(_.providerEnvironment)).toList.sorted
        val body = CodexHeader + "[mcp_servers.cq]\ncommand = " + quoted(executable.toString) +
          "\nargs = [" + args.map(quoted).mkString(", ") + "]\ncwd = " + quoted(project.toString) +
          "\nenv_vars = [" + forwarded.map(quoted).mkString(", ") + "]\nstartup_timeout_sec = 45\ntool_timeout_sec = " + DispatchWaits.AttachedHarnessSeconds + "\n"
        val hooksFile = root.resolve(CodexHooks)
        val hooks = if (Files.exists(hooksFile)) parser.parse(HostFiles.text(hooksFile.toRealPath(), MaxConfigBytes)).fold(throw _, identity) else Json.obj()
        List(CommandAsset(Path.of(".codex/config.toml"), body),
          CommandAsset(CodexHooks, DriverAssets.hooks(hooks, executable, harness, CodexHooks.toString).spaces2 + "\n"))
      case Harness.Pi =>
        List(PiAssets.extension,
          CommandAsset(Path.of(".pi/extensions/cq-host.json"), command.deepMerge(Json.obj("directory" -> Json.fromString(project.toString),
            "tools" -> Json.arr(schemas.attachedTools*))).spaces2 + "\n"))
    }
    integration ++ workflows.commands(harness) ++ DriverAssets.commands(harness)
  }
}
