package cq.server

import cq.api.*
import cq.host.{CommandAsset, DriverAssets, HostFiles, WorkflowAssets}
import io.circe.{Json, parser}
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.{Files, Path}
import scala.util.Using

final class AttachedAssets(schemas: McpSchemas, workflows: WorkflowAssets) {
  private val MaxConfigBytes = 1024 * 1024
  private val CodexHeader = "# Generated by cq configure; contains no credentials.\n"
  private val ClaudeSettings = Path.of(".claude/settings.local.json")
  private val CodexHooks = Path.of(".codex/hooks.json")
  private def quoted(value: String): String = Json.fromString(value).noSpaces
  private def resource: String = Using.resource(Option(getClass.getResourceAsStream("/cq/pi-attached.mjs"))
    .getOrElse(throw new IllegalStateException("Installed Pi attached extension is missing"))) { stream =>
    val bytes = stream.readNBytes(MaxConfigBytes + 1)
    require(bytes.length <= MaxConfigBytes, "Installed Pi extension exceeds its byte bound")
    UTF_8.newDecoder().decode(java.nio.ByteBuffer.wrap(bytes)).toString
  }
  def write(harness: Harness, root: Path, settingsPath: Path, executable: Path, replace: Boolean, replaceStatusLine: Boolean): List[Path] = {
    require(executable.isAbsolute && Files.isExecutable(executable) && Files.isRegularFile(executable), "CQ executable must be an absolute executable file")
    val settings = HostFiles.read(settingsPath, SupervisorSettings_JsonCodec, MaxConfigBytes)
    require(settings.harnesses.exists(_.harness == harness), "Settings do not include this harness route")
    val args = List("host", harness.toString.toLowerCase, "--settings", settingsPath.toString)
    val command = Json.obj("command" -> Json.fromString(executable.toString), "args" -> Json.arr(args.map(Json.fromString)*))
    val integration = harness match {
      case Harness.Claude =>
        val file = root.resolve(".mcp.json")
        val current = if (Files.exists(file)) parser.parse(HostFiles.text(file, MaxConfigBytes)).fold(throw _, identity) else Json.obj()
        require(current.isObject, "Claude MCP configuration must be an object")
        val servers = current.hcursor.downField("mcpServers").focus.getOrElse(Json.obj())
        require(servers.isObject, "Claude mcpServers must be an object")
        val value = command.deepMerge(Json.obj("type" -> Json.fromString("stdio")))
        require(servers.hcursor.downField("cq").focus.forall(_ == value) || replace, "Claude cq entry differs; use --replace to replace that entry")
        val localFile = root.resolve(".claude/settings.local.json")
        val local = if (Files.exists(localFile)) parser.parse(HostFiles.text(localFile, MaxConfigBytes)).fold(throw _, identity) else Json.obj()
        require(local.isObject, "Claude .claude/settings.local.json must be an object")
        val enabled = local.hcursor.downField("enabledMcpjsonServers").focus.getOrElse(Json.arr())
        require(enabled.isArray, "Claude enabledMcpjsonServers in .claude/settings.local.json must be an array")
        val cq = Json.fromString("cq")
        val approved = if (enabled.asArray.exists(_.contains(cq))) enabled else enabled.mapArray(_ :+ cq)
        // Claude records a declined server in disabledMcpjsonServers, which overrides the approval; remove only the cq entry.
        val disabled = local.hcursor.downField("disabledMcpjsonServers").focus
        require(disabled.forall(_.isArray), "Claude disabledMcpjsonServers in .claude/settings.local.json must be an array")
        val settingsLocal = disabled.fold(local)(value => local.mapObject(_.add("disabledMcpjsonServers", value.mapArray(_.filterNot(_ == cq)))))
        val driven = DriverAssets.statusLine(DriverAssets.hooks(settingsLocal.mapObject(_.add("enabledMcpjsonServers", approved)), executable, harness, ClaudeSettings.toString),
          executable, replaceStatusLine, ClaudeSettings.toString)
        List(CommandAsset(Path.of(".mcp.json"), current.mapObject(_.add("mcpServers", servers.mapObject(_.add("cq", value)))).spaces2 + "\n"),
          CommandAsset(ClaudeSettings, driven.spaces2 + "\n"))
      case Harness.Codex =>
        val file = root.resolve(".codex/config.toml")
        val forwarded = (Set("CQ_TOKEN", "CQ_TOKEN_FILE", "CQ_SETTINGS", "CODEX_HOME") ++ settings.harnesses.flatMap(_.providerEnvironment)).toList.sorted
        val body = CodexHeader + "[mcp_servers.cq]\ncommand = " + quoted(executable.toString) +
          "\nargs = [" + args.map(quoted).mkString(", ") + "]\ncwd = " + quoted(root.toString) +
          "\nenv_vars = [" + forwarded.map(quoted).mkString(", ") + "]\nstartup_timeout_sec = 45\ntool_timeout_sec = 35\n"
        require(!Files.exists(file) || HostFiles.text(file, MaxConfigBytes).startsWith(CodexHeader),
          "Existing .codex/config.toml is user-owned. Export into an empty directory and merge its mcp_servers.cq table into this file; CQ will not overwrite unrelated TOML settings")
        val hooksFile = root.resolve(CodexHooks)
        val hooks = if (Files.exists(hooksFile)) parser.parse(HostFiles.text(hooksFile, MaxConfigBytes)).fold(throw _, identity) else Json.obj()
        List(CommandAsset(Path.of(".codex/config.toml"), body),
          CommandAsset(CodexHooks, DriverAssets.hooks(hooks, executable, harness, CodexHooks.toString).spaces2 + "\n"))
      case Harness.Pi =>
        List(CommandAsset(Path.of(".pi/extensions/cq-host.js"), resource),
          CommandAsset(Path.of(".pi/extensions/cq-host.json"), command.deepMerge(Json.obj("directory" -> Json.fromString(root.toString),
            "tools" -> Json.arr(schemas.attachedTools*))).spaces2 + "\n"))
    }
    // JSON configuration CQ merges into is rewritten in place; every other asset is a generated file guarded by --replace.
    val merged = integration.map(_.path).filter(path => harness == Harness.Claude || path == CodexHooks).toSet
    workflows.writeAssets(integration ++ workflows.commands(harness) ++ DriverAssets.commands(harness), root, replace, merged)
  }
}
